---
- hosts: p50
  remote_user: root
  tasks:
    - import_role:
        name: karmab.kcli-modules
    - name: Create a vm
      kvirt_vm:
        name: foss
        state: present
        profile: rhel7.5_x86_64.qcow2
        parameters:
         memory: 2048

